version: '3.4'

services:
  frznupload.web:
    image: ${DOCKER_REGISTRY-}frznuploadweb
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "22340:22340"
    networks:
      - internal
    volumes:
      - "./fritzen.xyz.pfx:/certs/fritzen.xyz.pfx"
      - "./files/:/files/"
    depends_on:
      - sql

  sql:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    hostname: 'sql'
    ports:
      - "3306:3306"
    restart: "unless-stopped"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
      - MSSQL_PID=Express
    networks:
      - internal

networks:
  internal: