// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using frznUpload.Web.Data;

namespace frznUpload.Web.Migrations
{
    [DbContext(typeof(frznUploadContext))]
    [Migration("20190625152408_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview6.19304.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("frznUpload.Web.Data.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("File_extension");

                    b.Property<string>("Filename");

                    b.Property<string>("Identifier");

                    b.Property<int>("Size");

                    b.Property<long>("Tags");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("frznUpload.Web.Data.Share", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("File_identifier");

                    b.Property<bool>("First_view");

                    b.Property<string>("First_view_cookie");

                    b.Property<bool>("Public");

                    b.Property<bool>("Public_registered");

                    b.Property<string>("Share_id");

                    b.Property<string>("Whitelist");

                    b.Property<bool>("Whitelisted");

                    b.HasKey("Id");

                    b.ToTable("Shares");
                });

            modelBuilder.Entity("frznUpload.Web.Data.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Last_used");

                    b.Property<byte[]>("Signature");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("frznUpload.Web.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Hash");

                    b.Property<string>("Name");

                    b.Property<string>("Salt");

                    b.Property<string>("Two_fa_secret");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
